name: Oromie
highlighter: rouge
markdown: kramdown
excerpt_separator: <!--more-->
gems: [jekyll-paginate]
paginate: 3
paginate_path: "blog/page:num"
sass:
    sass_dir: _sass
    style: :compressed
url: 'http://www.oromie.com.br/oromiedevel.github.io/'
